---
- name: Librdkafka | ensure build requirements are met
  ansible.builtin.apt:
    name:
      - bash
      - build-essential
      - cmake
      - zlib1g
      - zlib1g-dev
      - libssl-dev
    state: present

- name: Librdkafka | check for existing installations
  ansible.builtin.find:
    path: /usr/local/lib
    pattern: "*rdkafka*"
    file_type: file
    recurse: yes
  register: librdkafka_result

- name: Librdkafka | cleanup existing installation
  when: librdkafka_cleanup_if_exists and librdkafka_result.matched > 1
  block: 
    - name:  Librdkafka | remove static files
      ansible.builtin.file:
        name: "{{ item.path }}"
        state: absent
      loop: "{{ librdkafka_result.files }}"

    - name:  Librdkafka | remove any existing apt version
      ansible.builtin.apt:
        name: librdkafka*
        state: absent

- name: Librdkafka | install library
  when: librdkafka_result.matched < 1 or librdkafka_cleanup_if_exists
  block:
    - name: Librdkafka | download archive from GitHub
      ansible.builtin.get_url: 
        url: "https://github.com/edenhill/librdkafka/archive/{{ librdkafka_version }}.tar.gz"
        dest: "/tmp/librdkafka.tar.gz"
        checksum: "{{ librdkafka_checksum | default(omit) }}"
        force: "{{ librdkafka_cleanup_if_exists }}"
        mode: 0775

    - name: Librdkafka | create destination folder
      ansible.builtin.file:
        path: /tmp/librdkafka-{{ librdkafka_version }}
        state: directory
        mode: 0775

    - name: Librdkafka | extract .tar archive
      ansible.builtin.unarchive:
        src: /tmp/librdkafka.tar.gz
        dest: /tmp/librdkafka-{{ librdkafka_version }}
        extra_opts: [--strip-components=1]
        remote_src: yes
        mode: 0775

    - name: Librdkafka | compile source code
      ansible.builtin.shell:
        cmd: |
          set -o pipefail
          ./configure {{ librdkafka_build_opts | default('') }} && \
          make -j{{ ansible_processor_cores }} && \
          make install
        chdir: /tmp/librdkafka-{{ librdkafka_version }}/
        warn: no
        executable: /bin/bash
      tags: ['molecule-idempotence-notest', 'skip_ansible_lint']

    - name: Librdkafka | cleanup tmp
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/librdkafka.tar.gz
        - "/tmp/librdkafka-{{ librdkafka_version }}"
