---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    librdkafka_version: "{{ lookup('env', 'LIBRDKAFKA_VERSION') }}"
    librdkafka_checksum: "{{ lookup('env', 'LIBRDKAFKA_CHECKSUM') }}"

  roles:
    - role: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}"
