---
- name: Prepare
  hosts: instance
  gather_facts: yes
  become: yes
  tasks:
    - name: Install python dependencies
      ansible.builtin.apt: 
        name: 
          - python3-minimal
          - python3-apt
        update_cache: yes
