---
- name: Verify
  hosts: all
  gather_facts: no
  tasks: 
    - name: Look for compiled assets
      ansible.builtin.find:
        path: /usr/local/lib
        pattern: "*rdkafka*"
        file_type: file
        recurse: yes
      register: librdkafka_search

    - name: Ensure search has results
      ansible.builtin.assert:
        that: librdkafka_search.matched >= 4
